### ISSUE TITLE
Create VM image with OAM+Crossplane+K8s

### ISSUE THREAD

**Issue by artursouza** [Azure/azure-oam-solution#1]
Create a VM image that has OAM + Crossplane + K8s installed. For Crossplane, Azure provider must be installed. Crossplane should work in remote mode, which means apps will be deployed to a remote AKS cluster.

How to setup Crossplane: https://github.com/crossplane/crossplane/blob/master/docs/getting-started/install.md

- [x] Install tools (kubectl, helm)
- [x] Install minikube and manage lifetime
- [x] Install Crossplane (currently using v0.10.0)
- [x] Configure Azure credentials
- [x] Configure Azure credentials securely (don't print creds to console, etc)
- [x] Provision Remote cluster and verify connectivity
- [ ] Document steps to use this script to deploy flight tracker
